import type { Monster } from "./types";

// Source list as provided by the user (number, name, zone) is preserved
// exactly in `zone`. Where research turned up a different, better-verified
// zone or a known in-game coordinate, that goes in `verifiedZone` / `pin`,
// with `zoneNote` explaining the discrepancy - the app routes/maps using
// the verified data but never silently drops what the user gave it.
//
// Coordinates are the in-game map's X,Y scale (~1-42 per axis). Confidence:
// "confirmed" = pinned by a class hunting-log page at a matching level,
// "common"/"approx" = consistently reported but not hunting-log-pinned or
// with multiple candidate spots, "user" = placed by the player in this app.
export const MONSTERS: Monster[] = [
  {
    id: 1,
    name: "Cù-sìth",
    zone: "Unknown",
    category: "unverified",
    zoneNote:
      "No monster by this name could be verified in FFXIV (checked hunting logs, the full Coerthas Central Highlands bestiary, and species lists). It may be a transcription error or mixed up with another game. Left out of the route until you confirm the real name/zone.",
  },
  { id: 2, name: "Squirrel", zone: "Central Shroud", category: "overworld", pin: { x: 22.3, y: 17.6, confidence: "confirmed" } },
  { id: 3, name: "Lamb", zone: "Middle La Noscea", category: "overworld", pin: { x: 22.2, y: 25.6, confidence: "confirmed" } },
  { id: 4, name: "Pugil", zone: "Middle La Noscea", category: "overworld" },
  { id: 5, name: "Opo-opo", zone: "North Shroud", category: "overworld", pin: { x: 27, y: 23, confidence: "confirmed" } },
  { id: 6, name: "Dodo", zone: "Lower La Noscea", category: "overworld", pin: { x: 29, y: 19, confidence: "confirmed" } },
  { id: 7, name: "Coblyn", zone: "Western Thanalan", category: "overworld", pin: { x: 26.5, y: 16.5, confidence: "confirmed" } },
  { id: 8, name: "Diremite", zone: "Central Shroud", category: "overworld", pin: { x: 19, y: 18, confidence: "confirmed" } },
  { id: 9, name: "Megalocrab", zone: "Middle La Noscea", category: "overworld", pin: { x: 14, y: 14, confidence: "common" } },
  {
    id: 10,
    name: "Wespe",
    zone: "Central Thanalan",
    verifiedZone: "Middle La Noscea",
    category: "overworld",
    pin: { x: 14, y: 13, confidence: "approx" },
    zoneNote:
      "Sources place the base 'Wespe' at Three-malm Bend in Middle La Noscea (same landmark as Megalocrab), not Central Thanalan.",
  },
  { id: 11, name: "Vulture", zone: "Western Thanalan", category: "overworld", pin: { x: 21, y: 25, confidence: "confirmed" } },
  { id: 12, name: "Mandragora", zone: "Middle La Noscea", category: "overworld", pin: { x: 22, y: 18, confidence: "confirmed" } },
  { id: 13, name: "Geshunpest", zone: "Central Shroud", category: "overworld" },
  { id: 14, name: "Puk", zone: "Middle La Noscea", category: "overworld", pin: { x: 20, y: 19, confidence: "confirmed" } },
  { id: 15, name: "Crab", zone: "Western Thanalan", category: "overworld", pin: { x: 15, y: 15, confidence: "common" } },
  { id: 16, name: "Mantis", zone: "Western La Noscea", category: "overworld", pin: { x: 22, y: 21, confidence: "confirmed" } },
  { id: 17, name: "Slime", zone: "Copperbell Mines", category: "dungeon" },
  { id: 18, name: "Dullahan", zone: "Halatali", category: "dungeon" },
  { id: 19, name: "Bat", zone: "Lower La Noscea", category: "overworld", pin: { x: 26.5, y: 15.5, confidence: "confirmed" } },
  {
    id: 20,
    name: "Flying Trap",
    zone: "Central Shroud",
    category: "overworld",
    zoneNote: "No Flying Trap-genus monster near this checklist level was found in Central Shroud in current sources - kept as given, treat with caution.",
  },
  {
    id: 21,
    name: "Ziz",
    zone: "Western La Noscea",
    verifiedZone: "North Shroud",
    category: "overworld",
    pin: { x: 16, y: 27, confidence: "approx" },
    zoneNote: "Ziz is reported in North Shroud (Alder Springs); Western La Noscea's mob roster doesn't include a Ziz-type monster.",
  },
  {
    id: 22,
    name: "Sabotender",
    zone: "Western Thanalan",
    verifiedZone: "Southern Thanalan",
    category: "overworld",
    pin: { x: 17, y: 15, confidence: "approx" },
    zoneNote: "Sabotender is reported in Southern Thanalan (Broken Water), not Western Thanalan.",
  },
  { id: 23, name: "Golem", zone: "Southern Thanalan", category: "overworld", pin: { x: 22.1, y: 11.7, confidence: "confirmed" } },
  { id: 24, name: "Apkallu", zone: "Eastern La Noscea", category: "overworld", pin: { x: 28, y: 35, confidence: "confirmed" } },
  {
    id: 25,
    name: "Adamantoise",
    zone: "Central Thanalan",
    verifiedZone: "South Shroud",
    category: "overworld",
    zoneNote:
      "The hunting-log 'Adamantoise' (lvl 30-33) is in South Shroud (Lower Paths/Rootslake); Central Thanalan only has the level-50 'Alpha Adamantoise' mark.",
  },
  { id: 26, name: "Buffalo", zone: "Middle La Noscea", category: "overworld", pin: { x: 18, y: 17, confidence: "confirmed" } },
  { id: 27, name: "Uragnite", zone: "Western Thanalan", category: "overworld", pin: { x: 17, y: 14, confidence: "confirmed" } },
  { id: 28, name: "Worm", zone: "Southern Thanalan", category: "overworld", pin: { x: 13.2, y: 34.3, confidence: "confirmed" }, zoneNote: "Alternate spawns also reported around (16, 34) and (23, 32)." },
  { id: 29, name: "Spriggan", zone: "Central Thanalan", category: "overworld", pin: { x: 17, y: 23, confidence: "common" } },
  {
    id: 30,
    name: "Goobbue",
    zone: "Lower La Noscea",
    category: "overworld",
    pin: { x: 22.8, y: 24.6, confidence: "approx" },
    zoneNote: "Multiple candidate spawn points reported for Mossless Goobbue; pin marks one of them.",
  },
  {
    id: 31,
    name: "Gigantoad",
    zone: "Lower La Noscea",
    verifiedZone: "Eastern La Noscea",
    category: "overworld",
    pin: { x: 18.5, y: 26, confidence: "confirmed" },
    zoneNote: "Gigantoad is at Raincatcher Gully in Eastern La Noscea; it isn't part of Lower La Noscea's roster.",
  },
  { id: 32, name: "Colibri", zone: "Eastern La Noscea", category: "overworld", pin: { x: 30, y: 24.5, confidence: "confirmed" } },
  { id: 33, name: "Coeurl", zone: "Outer La Noscea", category: "overworld", pin: { x: 14, y: 14, confidence: "confirmed" } },
  { id: 34, name: "Raptor", zone: "Central Shroud", category: "overworld", pin: { x: 12, y: 19, confidence: "common" } },
  {
    id: 35,
    name: "Drake",
    zone: "Southern Thanalan",
    category: "overworld",
    pin: { x: 29.5, y: 19.5, confidence: "approx" },
    zoneNote: "'Battle Drake' at Zahar'ak used as the closest level match; 'Sundrake' (25, 38) is an alternate candidate.",
  },
  {
    id: 36,
    name: "Treant",
    zone: "Central Shroud",
    verifiedZone: "South Shroud",
    category: "overworld",
    zoneNote: "The level-appropriate Treant is reported in South Shroud; Central Shroud's own Treant-family mobs are a different level range.",
  },
  { id: 37, name: "Antling", zone: "Cutter's Cry", category: "dungeon" },
  { id: 38, name: "Chimera", zone: "Cutter's Cry", category: "dungeon" },
  {
    id: 39,
    name: "Morbol",
    zone: "Central Shroud",
    verifiedZone: "East Shroud",
    category: "overworld",
    pin: { x: 23, y: 21, confidence: "confirmed" },
    zoneNote: "Morbol (lvl 43-48) is at Larkscall in East Shroud; Central Shroud only has the level-50 'Alpha Morbol'.",
  },
  { id: 40, name: "Ghost", zone: "Middle La Noscea", category: "overworld", pin: { x: 20, y: 19, confidence: "confirmed" } },
  {
    id: 41,
    name: "Salamander",
    zone: "Central Shroud",
    verifiedZone: "Upper La Noscea",
    category: "overworld",
    pin: { x: 28, y: 24, confidence: "approx" },
    zoneNote:
      "Salamander (lvl 34-37) is reported at Bronze Lake in Upper La Noscea - a zone not in your original list at all. Central Shroud only has the much lower-level 'Black Eft'.",
  },
  { id: 42, name: "Cobra", zone: "Mor Dhona", category: "overworld", pin: { x: 25, y: 9.5, confidence: "confirmed" } },
  { id: 43, name: "Hydra", zone: "A Relic Reborn: The Hydra", category: "dungeon" },
  { id: 44, name: "Damselfly", zone: "The Lost City of Amdapor", category: "dungeon" },
  { id: 45, name: "Rotting Goobbue", zone: "The Lost City of Amdapor", category: "dungeon" },
  { id: 46, name: "Zu", zone: "Pharos Sirius", category: "dungeon" },
  { id: 47, name: "Ice golem", zone: "Snowcloak", category: "dungeon" },
  { id: 48, name: "Karlabos", zone: "Sastasha (Hard)", category: "dungeon" },
  { id: 49, name: "Rafflesia", zone: "the Second Coil of Bahamut - Turn 1", category: "dungeon" },
  { id: 50, name: "Behemoth", zone: "the Labyrinth of the Ancients", category: "dungeon" },
];
